language: elixir

elixir:
  - 1.9.4

otp_release:
  - 22.1.4

env:
  - MIX_ENV=test

script:
  - mix test

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test

after_script:
  - MIX_ENV=test mix coveralls.travis
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report 
